export const colors = {
    primary: 'white',
    secondary: '#DEE2E6',
    background: 'transparent',
    backgroundDark: '#000',
    surface: '#4B4A4BFF',
    transparent: 'transparent',
    transparentWhite: '#4B4A4BFF',
    transparentBlack: '#4B4A4BFF',
    purple: '#6e11b0',
    text: {
        primary: 'white',
        secondary: '#DEE2E6',
        light: '#1e2022',
    },
    error: '#ffb500',
    success: '#28A745',
    border: '#DEE2E6',
    input: {
        background: '#ad46ff',
        border: '#ad46ff',
    },
    bgGradient: ['#6e11b0', '#51a2ff'],
    // bgGradient: ['#6e11b0', '#ad46ff', '#2b7fff'],
    // bgGradient: ['#6e11b0', '#ad46ff', '#ad46ff', '#c27aff'],
    button: {
        primary: '#c27aff',
        secondary: '#c27aff',
        text: 'black',
    },
} as const;
